source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~> 2.2.4'
gem 'rspec'
gem 'jekyll', '~> 3.9.5'
gem 'jekyll-theme-cayman', '~> 0.2.0'
gem 'jekyll-remote-theme', '~> 0.4.3'
gem 'kramdown-parser-gfm', '~> 1.1.0'
gem 'kramdown', '~> 2.4.0'
gem "webrick", "~> 1.8"
